### DISCUSSION TITLE
How to control shower alert via api?

### DISCUSSION THREAD

**Discussion by wojtulab** [emsesp/EMS-ESP32#2168] [General]
Hello,
I can't find any example how to control shower_alert via api. Could you give me a hint?

**Comment by proddy** [comment]
sure. What are you trying to achieve?

**Comment by wojtulab** [comment]
I would like to turn on/off shower alert via automation in home assistant based on rules/time etc
I am thinking about 

HA: configuration.yaml
```
rest_command:
  set_shower_alert:
    url: "http://<EMS_IP>/api/system/settings"
    method: POST
    headers:
      authorization: 'xyz'
      Content-Type: "application/json"
    payload: '{"showerAlert": {{ shower_alert_status }}}'
```

```
template:
  - switch:
      - name: "Shower Alert"
        turn_on:
          service: rest_command.set_shower_alert
          data:
            shower_alert_status: "true"
        turn_off:
          service: rest_command.set_shower_alert
          data:
            shower_alert_status: "false"
```
or just cURL:
```
curl -X POST http://<EMS-IP>/api/system/settings \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer xyz" \
     -d '{"showerAlert": false}'

```
this curl not working... why? Is it possible to enable/implement that?
