### DISCUSSION TITLE
Is there a chance to read/write the start and end of vacation? (as possible in the myDevice App)

### DISCUSSION THREAD

**Discussion by harvey637** [emsesp/EMS-ESP32#2467] [Q&A]
Hi,
sometime ago I recognised the readable "vacation" boolean. I played around with setting the vacation start and end and some parameters of the vacation e.g. the vacation temperature in the Buderus MyDevice App. My heatpump is reacting accordingly, it sets the temperature to the vacation_temperature at the day of the vacation at 00:00. Also in the ems-esp the varaible "vacation" is set to true.
The app gives me the opportunity by a single question to terminate the vacation, which than goes back to normal program modus.

My question is, is this (setting of vacation_start_day, vacation_end_day, possibly also the vacation_temperature) readable AND WRITEABLE in the ems-esp webfrontend/api?

This would be a great help in centralizing my vacations on a single point (e.g. calendar) to control all my devices (heatpump, blinds, lights,....) by this variables.
Debug output from the ems-esp can be provided if helpful.

Thank You
Harvey

**Comment by Sbried** [comment]
The holiday mode is just readable. It is set by the controller when a holiday starts/ends.
There is no option given by Buderus to use just this "switch". You will have to set start/end, temperatures and so on

**Comment by harvey637** [comment]
Hi, I tested a bit more:
Created custom entities for my RC300 like:
_name_ : _device_id_ : _type_id_ : _offset_ : _writable_ : _size_ : _scale_ : _unit_ 
Holiday_Start_Year       : 0x10 ; 0x269 :   0 : yes : uint8 : 1 : -
Holiday_Start_Month   : 0x10 ; 0x269 :   1 : yes : uint8 : 1 : -
Holiday_Start_Day       : 0x10 ; 0x269 :   2 : yes : uint8 : 1 : -
Holiday_End_Year        : 0x10 ; 0x269 :   3 : yes : uint8 : 1 : -
Holiday_End_Month   : 0x10 ; 0x269 :   4 : yes : uint8 : 1 : -
Holiday_End_Day        : 0x10 ; 0x269 :   5 : yes : uint8 : 1 : -
Holiday_unknown       : 0x10 ; 0x269 :   6 : yes : uint8 : 1 : -
Holiday_Temperature : 0x10 ; 0x269 :   7 : yes : uint8 : 1 : °C

When I write values in EMS-ESP they are transported into the app, when I change values in the app they are reflected in the EMS-ESP.

The year starts at 2000, so "25" is year "2025".
Month is 01-12, day 01-31 (31 in a month with less days is pushed into next month)
Delete holiday with start and end date like 17-01-01.
I have no idea about the unkonwn offset or other offsets. 
I cannot handle anything other than "in_house", "manual temperature", possibly this are the other offsets, but I have no clue.

So with writing to this curtom entities I can set (most params, but the essential ones) holiday via api, which is great!!!!!
For me I dont need any other holidays, as I can set single day holidays everyday on a holiday eg. if tomorrow is holiday I set it shortly after midnight.

**Reply by MichaelDvP** [reply]
The other offsets:
6 - hc mode enum: 1-auto, 2-temp (from offset 7), 3-off, 4-eco
8- dhw mode enum: 1-auto- 2-off, 3-eco, 4-low, 5-high
9- hc1 holiday  off/on (0/1) 
10- hc2 holiday  off/on (0/1) 
11- hc3 holiday  off/on (0/1) 
12- hc4 holiday  off/on (0/1) 
13- dhw1 holiday  off/on (0/1)
14- dhw2 holiday  off/on (0/1) 

It was all (holidaymodes, timer programs) in my testbuild, but i've learned that nobody needs it and deleted the branch.

**Reply by drheck** [reply]
Hello [harvey637](https://github.com/harvey637),
i have bought EMS-ESP in order to use it for the same purpose and because there is no MB-Lan module available...
Am I correct in understanding that the custom settings mentioned allow you to set the two heating circuits (I've already managed that myself) and the hot water to the vacation settings?
I have the CW400 control unit with two heating circuits and a hot water tank.
Since I am often away on irregular trips, I would like to use an API call from homebridge to set the two heating circuits to manual+18 degrees and switch off the hot water+disinfection.
And switch it back on again.
As I said, this works for hc1+hc2.
But what exactly do you have to set to change the hot water?
It would be great if you could explain this to me in more detail.
thank you,
Peter

**Reply by harvey637** [reply]
@DrHeck
As I have no HotWater in my EMS-ESP System I never played with settings other than my HC1 as mentioned in the last post.
You already managed the settings of the heating circuits. My guess (and hope) would be that HotWater is similar. Sorry for no more help.
Good Luck
Harvey637

**Reply by drheck** [reply]
@harvey637 
Thank you. 
@MichaelDvP:
Perhaps you can explain me more?
I want to disable the hot water without disabeling the desinfection.
If i set the dhw operating mode from own_prog to off, it seems that nothing happens...
Thanks a lot,
Peter

**Reply by MichaelDvP** [reply]
> Perhaps you can explain me more?

Sorry, no, i have a different thermostat (RC35) with other settings. 

If you find a usefull setting in the thermostat that is not in emsesp, i can help to find this in the log and can add to emsesp.

**Reply by drheck** [reply]
Okay. Thank you. I will look in the next days...

**Reply by bimbalasim** [reply]
Observe same prob here on RC310 as @drheck. Looks like dhw1 never gets read, in contrast with hc1 and hc2 -- created PR #3033.

**Comment by JokerGermany** [comment]
If it helps:
This is my logic in Home Assistant for setting holiday:
```
metadata: {}
data:
  value: >-
    {{now().strftime('%d.%m.%Y')}}-31.12.{{as_timestamp(now()+timedelta(days=365))|
    timestamp_custom('%Y')}}
target:
  entity_id: text.ems_esp_thermostat_hc2_vacations
action: text.set_value
```
This is my logic for setting holiday off:
```
if:
  - condition: template
    value_template: >-
      {{as_timestamp(strptime(states('text.ems_esp_thermostat_hc2_vacations').split('-')[0],
      '%d.%m.%Y'))<as_timestamp(today_at())}}
then:
  - metadata: {}
    data:
      value: >-
        {{states('text.ems_esp_thermostat_hc2_vacations').split('-')[0]}}-{{as_timestamp(now()-timedelta(days=1))|
        timestamp_custom('%d.%m.%Y')}}
    target:
      entity_id: text.ems_esp_thermostat_hc2_vacations
    action: text.set_value
else:
  - metadata: {}
    data:
      value: >-
        {{as_timestamp(now()-timedelta(days=1))|timestamp_custom('%d.%m.%Y')}}-{{as_timestamp(now()-timedelta(days=1))|timestamp_custom('%d.%m.%Y')}}
    target:
      entity_id: text.ems_esp_thermostat_hc2_vacations
    action: text.set_value
```
