### DISCUSSION TITLE
How to set own program?

### DISCUSSION THREAD

**Discussion by JokerGermany** [emsesp/EMS-ESP32#2473] [Q&A] [answered]
Hi,
I want to use the auto function of my RC30.
I want to set it to 10:00-22:00 day on everyday?
How do I do it?

program => own1

My problem is "own1 program switchtime" 
I don't understand what the description means:
<nn> [ not_set | day hh:mm on|off ]

What means nn?
how do I "set" day to every day?

at the moment there is: 
00 mo 10:00 on

**Comment by MichaelDvP** [comment]
The timer has 42 entries, too much to create entities for each. We discussed that in #1594 and i've made a test-build with a json strucure to set the timer values: https://github.com/MichaelDvP/EMS-ESP32/releases/tag/test

The current setting is: you have to set each entry by number. Entering only the number reads the entry.
eg. now you have: `00 mo 10:00 on`
enter `01` without any parameter, than the field will show `01 mo 22:00 off` ( or something like that)
To change the complete program you have to send all 42 entries. Delete a entry (e.g. no 40) with `40 not_set`

**Reply by JokerGermany** [reply, marked as answer]
If i understand you correctly every time has to be seperat.
This means in my case (every day 10-22 day):
I need to send this own1 program switchtime commands:
```
01 mo 10:00 on
02 mo 22:00 off
03 tu 10:00 on
04 tu 22:00 off
05 we 10:00 on
06 we 22:00 off
07 th 10:00 on
08 th 22:00 off
09 fr 10:00 on
10 fr 22:00 off
11 sa 10:00 on
12 sa 22:00 off
13 su 10:00 on
14 su 22:00 off
```
And to be sure it would be clever sending 15-52 as not_set?

And for reading the data I need to send 1-42? Sounds like work XD

okay I wrote an quick and dirty automation in ha for reading the sensor data:
```
repeat:
  count: 42
  sequence:
    - if:
        - condition: template
          value_template: "{{ repeat.index < 11 }}"
      then:
        - action: text.set_value
          metadata: {}
          data:
            value: 0{{ repeat.index - 1 }}
          target:
            entity_id: text.ems_esp_thermostat_hc1_switchtime1
      else:
        - action: text.set_value
          metadata: {}
          data:
            value: "{{ repeat.index - 1 }}"
          target:
            entity_id: text.ems_esp_thermostat_hc1_switchtime1
    - delay:
        hours: 0
        minutes: 0
        seconds: 3
        milliseconds: 0
    - action: notify.matrix_ich
      data:
        message: >-
          hc1_switchtime1: {{ states('text.ems_esp_thermostat_hc1_switchtime1')
          }}
```

And this is the ha script which writes the data:
```
alias: EMS-ESP - own1 program switchtime
description: ""
triggers:
  - trigger: homeassistant
    event: start
conditions: []
actions:
  - repeat:
      sequence:
        - action: text.set_value
          metadata: {}
          data:
            value: "{{ repeat.item }}"
          target:
            entity_id: text.ems_esp_thermostat_hc1_switchtime1
      for_each:
        - 00 mo 10:00 on
        - 01 mo 22:00 off
        - 02 tu 10:00 on
        - 03 tu 22:00 off
        - 04 we 10:00 on
        - 05 we 22:00 off
        - 06 th 10:00 on
        - 07 th 22:00 off
        - 08 fr 10:00 on
        - 09 fr 22:00 off
        - 10 sa 10:00 on
        - 11 sa 22:00 off
        - 12 su 10:00 on
        - 13 su 22:00 off
  - variables:
      items: 14
  - repeat:
      sequence:
        - if:
            - condition: template
              value_template: "{{ repeat.index + items < 11 }}"
          then:
            - action: text.set_value
              metadata: {}
              data:
                value: 0{{ repeat.index - 1 + items }} not_set
              target:
                entity_id: text.ems_esp_thermostat_hc1_switchtime1
          else:
            - action: text.set_value
              metadata: {}
              data:
                value: "{{ repeat.index - 1 + items }} not_set"
              target:
                entity_id: text.ems_esp_thermostat_hc1_switchtime1
      until:
        - condition: template
          value_template: "{{ repeat.index + items > 42 }}"
mode: restart
```

BTW; I have A RC30 (looks like it depends on the RC...)
