### DISCUSSION TITLE
How do you integrate ems-esp into your home automation?

### DISCUSSION THREAD

**Discussion by bavo** [emsesp/EMS-ESP32#790] [Show and tell]
Just an idea tot start a discussion and share some ideas about how everyone uses this project to automate their home ... 

I'm interested and looking for some new ideas for everyone here 😄

**Comment by proddy** [comment]
good idea

**Comment by bavo** [comment]
I use a very basic setup using the home assistant integration. 

The thermostat still manages the heating inside my house. But when home assistant sees the hearing turn on and nobody is home, home assistant will turn the heating off. 

Drawback: The thermostat preheats my house so this is wasted money when nobody is home.

**Comment by bakboord4** [comment]
Use Gateway S32 with EMS-ESP2 and Home Assistant in basic reading only mode. 67 Entities learned me that the heating/warm water technology is complex and without proper knowledge too risky for me to make any changes.
HACS/Bosch thermostat and HA presence detection is used to control Home or Away (temperature) in EasyControl which for me is working beautifully.

**Comment by jtosic** [comment]
I have:
- Bosch ZWC24-MFA
- Bosch FR120
- Gateway S32

Everything is linked to Home Assistant via MQTT. The only thing I've managed to do is add:
- climate.thermostat_hc1
- select.thermostat_hc1_mode
to my dashboard and a few manual "automations" via Aqara Cube controller as well as presence detection via phone location.

What I would like to do is use one of the fancy thermostat cards but am unable to figure out how to map "eco" and "nofrost" modes to some valid Home Assistant HEVC values.

**Reply by proddy** [reply]
which card? If it's from HACS I'll see how to do it

**Reply by jtosic** [reply]
That'd be great if you could pull it off. Thanks!

I've tried the default one and all of the HACS thermostat cards:
- Dark Thermostat
- Simple Thermostat
- Climate thermostat card
- Better Thermostat UI

hoping one of them would let me remap, e.g. "eco" value to "fan_only" or "heat_cool" HVAC mode but had no luck.

**Comment by elRadix** [comment]
this is how I setup 2 climate entity for dhw with their mode and heating climate
and then use card in home assistant 
```
mqtt: 
  sensor:


  climate:
   - name: boiler
     unique_id: bosh_boiler 
     min_temp: 35
     max_temp: 60
     temp_step: 5
     current_temperature_topic: 'ems-esp/boiler_data_ww'
     temperature_state_topic: 'ems-esp/boiler_data_ww'
     temperature_command_topic: 'ems-esp/boiler/wwseltemp'
     temperature_command_template: >
       {{ '{"cmd":"wwseltemp ","data":'}}
       {{ value }}
       {{ '}'}}
     current_temperature_template: '{{ value_json.wwcurtemp }}'
     temperature_state_template: '{{ value_json.wwseltemp }}'
     mode_state_template: "{% if value_json.wwactivated == 'off' %} off {% else %} heat {% endif %}"
     mode_state_topic: 'ems-esp/boiler_data_ww'
     mode_command_topic: 'ems-esp/boiler/wwactivated'
     mode_command_template: >
       {{ '{"cmd":"wwactivated","data":"'}}
       {%- if value == 'off' -%}off{% else %}on{%- endif -%}
       {{'"}'}}
     modes:
       - 'heat'
       - 'off'
     # use fan mode as proxy to set comfort mode
     fan_mode_command_topic: 'ems-esp/boiler/wwcomfort'
     fan_mode_command_template: >
       {{ '{"cmd":"wwcomfort","data":"'}}
       {%- if value == 'eco' -%}eco{%-elif value == 'hot' -%}hot{%- else -%}intelligent{%- endif -%}
       {{'"}'}}
     fan_mode_state_topic: 'ems-esp/boiler_data_ww'
     fan_mode_state_template: '{{ value_json.wwcomfort }}'
     fan_modes:
       - 'eco'
       - 'hot'
       - 'intelligent'

   - name: heating
     unique_id: bosh_heating
     min_temp: 30
     max_temp: 80
     temp_step: 5
     current_temperature_topic: 'ems-esp/boiler_data'
     temperature_state_topic: 'ems-esp/boiler_data'
     temperature_command_topic: 'ems-esp/boiler'
     temperature_command_template: >
       {{ '{"cmd":"heatingtemp","data":'}}
       {{ value }}
       {{ '}'}}
     current_temperature_template: '{{ value_json.curflowtemp }}'
     temperature_state_template: '{{ value_json.heatingtemp }}'
     mode_state_template: "{% if value_json.heatingactivated == 'off' %} off {% else %} heat {% endif %}"
     mode_state_topic: 'ems-esp/boiler_data'
     mode_command_topic: 'ems-esp/boiler'
     mode_command_template: >
       {{ '{"cmd":"heatingactivated","data":"'}}
       {%- if value == 'off' -%}off{% else %}on{%- endif -%}
       {{'"}'}}
     modes:
       - 'heat'
       - 'off'

```

and hacs card
https://github.com/nervetattoo/simple-thermostat


![SmartSelect_20230207_172244_Home Assistant](https://user-images.githubusercontent.com/6258894/217302984-a9f48a09-f638-4931-90a8-d0b4e80fada9.jpg)


```
type: custom:simple-thermostat
entity: climate.boiler
sensors:
  - id: state
    label: State
    template: '{{hvac_action}}'
label:
  state: Warm Water
layout:
  mode:
    names: true
    icons: true
    headings: false
  step: column
step_size: '1'
control:
  hvac:
    'off':
      name: Warm Water Off
    heat:
      name: Warm Water On
  fan:
    eco:
      name: eco
    hot:
      name: hot
    intelligent:
      name: smart
decimals: '1'
hide:
  state: false
header:
  toggle:
    entity: switch.ketel
    name: power
  name: Boiler
view_layout:
  position: main
```
