### DISCUSSION TITLE
Calculate Costs for heating and water

### DISCUSSION THREAD

**Discussion by zibous** [emsesp/EMS-ESP32#977] [General]
**Question**
I would like the cost of water heating and determine the heating costs.

![heizung2021](https://user-images.githubusercontent.com/30198737/158141214-4b503116-89cb-4fa7-a402-c1841ca8bcc3.png)

I record the electricity consumption, gas consumption and also the hot water consumption via sensors and the data is available.

As I understand it, the heating circuit is disconnecte when the Boiler is heated, so it should be possible to split determining hot water and heating circuit preparation.

I want to calculate

- Percentage of energy demand for heating
- Percentage of energy demand hot water
- Proportion of gas volume heating
- Percentage of gas volume for hot water

Unfortunately, I can't find a way to do that would be grateful if someone could help me.

**Screenshots**

**Energy Consumption**
![energie_heating](https://user-images.githubusercontent.com/30198737/158140470-75edcad3-3965-4b58-b2b3-7445bee9d189.png)

**Gas per hour**
![gas-per-h](https://user-images.githubusercontent.com/30198737/158140517-c693f1e3-62e8-431d-a08e-5eefe75b2f93.png)

**Water per hour**
![water-per-h](https://user-images.githubusercontent.com/30198737/158140542-f6b9bf26-c3ff-4f12-b8f7-eba08119b3e7.png)

**Device information**
```
{
  "System": {
    "version": "3.4.0b8",
    "uptime": "002+08:13:45.736",
    "uptime (seconds)": 202425,
    "freemem": 149,
    "reset reason": "Software reset CPU / Software reset CPU",
    "temperature sensors": 0,
    "analog sensors": 0
  },
  "Network": {
    "connection": "WiFi",
	 ....
  },
  "Status": {
    "bus status": "connected",
    "bus protocol": "Buderus",
    "bus telegrams received (rx)": 204131,
    "bus reads (tx)": 46963,
    "bus writes (tx)": 5,
    "bus incomplete telegrams": 11,
    "bus reads failed": 291,
    "bus writes failed": 1,
    "bus rx line quality": 100,
    "bus tx line quality": 100,
    "MQTT status": "connected",
    "MQTT publishes": 64502,
    "MQTT publish fails": 0,
    "temperature sensors": 0,
    "temperature sensor reads": 0,
    "temperature sensor fails": 0,
    "analog sensors": 0,
    "analog sensor reads": 0,
    "analog sensor fails": 0,
    "API calls": 0,
    "API fails": 0,
    "syslog started": true,
    "syslog level": "debug",
    "syslog ip": "10.1.1.96",
    "syslog queue": 1
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "GBx72/Trendline/Cerapur/Greenstar Si/27i",
      "device id": "0x08",
      "product id": 123,
      "version": "07.00",
      "entities": 66,
      "handlers received": "0x10 0x11 0x15 0x1C 0x18 0x19 0x1A 0x35 0x34 0x2A",
      "handlers fetched": "0x14 0x16 0x33 0x26",
      "handlers pending": "0xC2 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA"
    },
    {
      "type": "Thermostat",
      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II",
      "device id": "0x10",
      "product id": 158,
      "version": "74.02",
      "entities": 40,
      "handlers received": "0x06 0xA2 0x02BA 0x02BB 0x02BC 0x02BD 0x02BE 0x02BF 0x02C0 0x031D 0x0267",
      "handlers fetched": "0x02A5 0x02B9 0x02AF 0x029B 0x02F5 0x031B 0x023A 0x0240",
      "handlers pending": "0xA3 0x12 0x0471 0x02A6 0x02B0 0x029C 0x0472 0x02A7 0x02B1 0x029D 0x0473 0x02A8 0x02B2 0x029E 0x0474 0x02A9 0x02B3 0x029F 0x0475 0x02AA 0x02B4 0x02A0 0x0476 0x02AB 0x02B5 0x02A1 0x0477 0x02AC 0x02B6 "
    },
    {
      "type": "Controller",
      "name": "BC25",
      "device id": "0x09",
      "product id": 125,
      "version": "03.05",
      "entities": 0
    }
  ]
}
```

**Comment by SpaceTeddy** [comment]
Hi zibous,
I do this in the following way with fhem and perl script.
- I count the gas value of the gas meter
- checking the ems_esp/boiler_data_wwcharging data every 10 seconds. If ems_esp/boiler_data_wwcharging eq "on" , I save the current gas value in a temp variable
- if ww is finished ems_esp/boiler_data_wwcharging eq "off" I save the actual gas value and substract it with the temp gas value. Then you got a gas value for each ww heating. 
- At the end of the day you can substract the gas value for the day with the ww gas consumption.

but, it get more complex if you have also other gas equipment in house,

greets 
Chris

**Comment by zibous** [comment]
> Hi zibous, I do this in the following way with fhem and perl script. 
>     * I count the gas value of the gas meter

Hi Chris,
Thanks for the tip. I did the following for testing:

```yaml
- platform: template
  sensors:
    ## see: https://github.com/emsesp/EMS-ESP32/issues/152
    heating_power_heizkreis_watt:
      friendly_name: "Aktuelle Leistung Raumheizung"
      unit_of_measurement: "W"
      value_template: >-
        {%- if is_state("binary_sensor.boiler_heating_active", "on") -%}
          {{ states('sensor.boiler_burner_current_power')|int(0) }}
        {%- else -%}
          0
        {%- endif -%}
      entity_id:
        - sensor.boiler_burner_current_power
        - binary_sensor.boiler_heating_active

    heating_power_warmwasser_watt:
      friendly_name: "Aktuelle Leistung Warmwasseraufbereitung"
      unit_of_measurement: "W"
      value_template: >-
        {%- if is_state("binary_sensor.boiler_dhw_charging", "on") -%}
          {{ states('sensor.boiler_burner_current_power')|int(0) }}
        {%- else -%}
          0
        {%- endif -%}
      entity_id:
        - sensor.boiler_burner_current_power
        - binary_sensor.boiler_dhw_charging
```


But if I evaluate the data, then I do not understand this, because the heater consumes energy and does not use gas? 

![Bildschirmfoto 2022-03-17 um 11 13 52](https://user-images.githubusercontent.com/30198737/158788542-e038809f-db0a-4994-a582-e1a6b94d3bec.png)

```sql

SELECT sum("value") FROM "kWh" WHERE ("entity_id" = 'wug_kilowattstunde_gas_stunde') AND $timeFilter GROUP BY time(1h) fill(none)
SELECT sum("value") FROM "autogen"."W" WHERE ("entity_id" = 'heating_power_heizkreis_watt') AND $timeFilter GROUP BY time(1h) fill(null)
SELECT sum("value") FROM "autogen"."W" WHERE ("entity_id" = 'heating_power_warmwasser_watt') AND $timeFilter GROUP BY time(1m) fill(null)

```

Either I make a consideration error or I can not get the right data from the EMS ESP.
