### ISSUE TITLE
Logavent HRV176 - Unrecognized EMS device (deviceID 0x51, productID 231)

### ISSUE THREAD

**Issue by Timon321** [emsesp/EMS-ESP32#1172]
### PROBLEM DESCRIPTION

I have a new device on my EMS-Bus, which is not recognized today running the latest dev-release 3.6.0-dev.9.

The device is the new Buderus Logavent HRV176. 

```lua
2023-05-08 14:06:05.444 I 17: [emsesp] Recognized new boiler with deviceID 0x08
2023-05-08 14:06:06.141 I 18: [emsesp] Recognized new thermostat with deviceID 0x10
2023-05-08 14:06:22.506 N 19: [emsesp] Unrecognized EMS device (deviceID 0x51, productID 231). Please report on GitHub.
2023-05-08 14:06:48.781 I 20: [emsesp] Recognized new mixer with deviceID 0x20`
```

What information is needed to adapt the ventilation system with the EMS-ESP?

![image](https://user-images.githubusercontent.com/7792233/236822006-be8aa811-d3ed-4a42-91a3-9c53a8589bf1.png)

**Comment by MichaelDvP** [comment]
Yes, ventilation systems are completly unknown. I think we should make a new device class for this.
Could you please tell what values this system reports and what settings it have.
And use telnet with `watch 51` for some minutes to see the telegrams from/to this device. 
If you change some paramters/settings while logging we could also see the setting telegrams. Please note when and what you have changed and tell it. 
Could you also add the `support info` from help-page.

**Comment by Timon321** [comment]
Support-Info:

```YAML
{
  "System Info": {
    "version": "3.6.0-dev.9",
    "platform": "ESP32",
    "uptime": "000+01:22:17.380",
    "uptime (seconds)": 4937,
    "free mem": 122,
    "max alloc": 39,
    "free app": 3,
    "reset reason": "Software reset CPU / Software reset CPU"
  },
  "Network Info": {
    "network": "Ethernet",
    "hostname": "ems-esp",
    "IPv4 address": "192.168.178.33/255.255.255.0",
    "IPv4 gateway": "192.168.178.1",
    "IPv4 nameserver": "192.168.178.1",
    "static ip config": false,
    "enable IPv6": false,
    "low bandwidth": false,
    "disable sleep": false,
    "enable MDNS": true,
    "enable CORS": false,
    "AP provision mode": "disconnected",
    "AP security": "wpa2",
    "AP ssid": "ems-esp"
  },
  "NTP Info": {
    "NTP status": "connected",
    "enabled": true,
    "server": "time.google.com",
    "tz label": "Europe/Berlin"
  },
  "OTA Info": {
    "enabled": true,
    "port": 8266
  },
  "MQTT Info": {
    "MQTT status": "connected",
    "MQTT publishes": 2252,
    "MQTT queued": 0,
    "MQTT publish fails": 0,
    "MQTT connects": 1,
    "enabled": true,
    "client id": "ems-esp",
    "keep alive": 60,
    "clean session": false,
    "entity format": 0,
    "base": "ems-esp",
    "discovery prefix": "homeassistant",
    "discovery type": 0,
    "nested format": 1,
    "ha enabled": true,
    "mqtt qos": 0,
    "mqtt retain": false,
    "publish time heartbeat": 60,
    "publish time boiler": 10,
    "publish time thermostat": 10,
    "publish time solar": 10,
    "publish time mixer": 10,
    "publish time other": 10,
    "publish time sensor": 10,
    "publish single": false,
    "publish2command": false,
    "send response": true
  },
  "Syslog Info": {
    "enabled": false
  },
  "Sensor Info": {
    "temperature sensors": 0,
    "temperature sensor reads": 0,
    "temperature sensor fails": 0,
    "analog sensors": 0,
    "analog sensor reads": 0,
    "analog sensor fails": 0
  },
  "API Info": {
    "API calls": 0,
    "API fails": 0
  },
  "Bus Info": {
    "bus status": "connected",
    "bus protocol": "Buderus",
    "bus telegrams received (rx)": 15053,
    "bus reads (tx)": 3106,
    "bus writes (tx)": 0,
    "bus incomplete telegrams": 6,
    "bus reads failed": 5,
    "bus writes failed": 0,
    "bus rx line quality": 100,
    "bus tx line quality": 100
  },
  "Settings": {
    "board profile": "E32",
    "locale": "de",
    "tx mode": 1,
    "ems bus id": 11,
    "shower timer": false,
    "shower alert": false,
    "hide led": false,
    "notoken api": false,
    "readonly mode": false,
    "fahrenheit": false,
    "dallas parasite": false,
    "bool format": 1,
    "bool dashboard": 1,
    "enum format": 1,
    "analog enabled": true,
    "telnet enabled": true,
    "max web log buffer": 50,
    "web log buffer": 5
  },
  "Devices": [
    {
      "type": "boiler",
      "name": "Enviline/Compress 6000AW/Hybrid 3000-7000iAW/SupraEco/Geo 5xx/WLW196i/WSW196i",
      "device id": "0x08",
      "product id": 172,
      "version": "03.03",
      "entities": 148,
      "handlers received": "0xBF 0xC2 0xD1 0xE3 0xE4 0xE5 0xE9 0x0494 0x0495 0x048F",
      "handlers fetched": "0x14 0xE6 0xEA 0x048D 0x048A 0x04A2 0x0485 0x0486 0x0492 0x0488 0x0484 0x048B 0x0491 0x0499 0x049C 0x049D",
      "handlers pending": "0x10 0x11 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A",
      "handlers ignored": "0xF7 0x04A0 0x02D6 0x0489 0x04AC 0x02CD 0x2E 0x3B"
    },
    {
      "type": "thermostat",
      "name": "Rego 3000/UI800",
      "device id": "0x10",
      "product id": 253,
      "version": "47.06",
      "entities": 51,
      "handlers received": "0x06 0x02BA 0x02BB 0x02BC 0x031D 0x0267",
      "handlers fetched": "0x02A5 0x02B9 0x02AF 0x029B 0x0471 0x02CC 0x02F5 0x023A 0x0240 0xBB 0x023E",
      "handlers pending": "0xA3 0xA2 0x12 0x13 0x02A6 0x02B0 0x029C 0x0472 0x02A7 0x02B1 0x029D 0x0473 0x02A8 0x02B2 0x029E 0x0474 0x02A9 0x02BD 0x02B3 0x029F 0x0475 0x02AA 0x02BE 0x02B4 0x02A0 0x0476 0x02AB 0x02BF 0x02B5 0x02A1 0x0477 0x02AC 0x02C0 0x02B6 0x02A2 0x0478 0x02CE 0x02D0 0x02D2 0x031B 0x031E",
      "handlers ignored": "0xE7 0x02E1 0x02EB 0x0507 0x0508 0x0509 0x050A 0x056B 0x061E 0x059D 0xF7 0x0589 0x0291 0xBF 0x0593"
    },
    {
      "type": "mixer",
      "name": "MM100",
      "device id": "0x20",
      "product id": 160,
      "version": "24.05",
      "entities": 4,
      "handlers received": "0x02D7",
      "handlers ignored": "0xD2 0xE2 0x0255 0xBF 0x02CD"
    },
    {
      "type": "unknown",
      "name": "unknown",
      "device id": "0x51",
      "product id": 231,
      "version": "53.02",
      "entities": 0,
      "handlers ignored": "0x0583 0xF9 0x0575 0x056B 0x0585 0x0586 0x0587 0x0588 0x058D 0x058E 0x058F 0x05CF 0x05D9 0x05E3 0xBF 0x0590"
    }
  ]
}
```

I will analyze the rest of the information and submit it by the end of the week at the latest. We have not yet moved into the house.
