### ISSUE TITLE
Thermostat HC1: can not set mode to OFF

### ISSUE THREAD

**Issue by bartplessers** [emsesp/EMS-ESP32#1486]
### PROBLEM DESCRIPTION

Recently I updated to EMS-ESP Version 3.6.4
I noticed that my home assistant automation to turn my heating system `OFF `does not work anymore.
Sample automation:

```
alias: Verwarming uit
description: ""
trigger:
  - platform: time
    at: "23:00:00"
condition: []
action:
  - device_id: fc7d3adde5ddb3170b13319aaae53729
    domain: climate
    entity_id: climate.thermostat_hc1
    type: set_hvac_mode
    hvac_mode: "off"
mode: single
```

HARDWARE:
BUDERUS Logamax PlusGB192iT40 - boiler
BUDERUS RC310 - thermostat
BUDERUS KM100 - gateway

Problem is that I can only change mode to `auto` or `heating`, but in both modes, the circulation pump keeps running (+/- 30W continiously) 

To save some power, I want to set my system OFF with ems-esp

### EXPECTED BEHAVIOUR

I want to set my system OFF with ems-esp
