### ISSUE TITLE
Track number of WiFi reconnects

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#2207]
There were reports of v3.7.0 losing connection to the WiFi network, so we added a new system entity to the MQTT heartbeat, counting the number of WiFi reconnects. It's called `WiFi reconnects` (wifireconnects) to keep consistent with the MQTT mqttconnects. The value is also shown in the WebUI. 

![image](https://github.com/user-attachments/assets/aa3f563a-e5ca-470e-8fd2-d1429fd06964)

For HA users if you want to get alerted when EMS-ESP drops from the WiFi network and reconnects, use a trigger like:

```yaml
alias: EMS-ESP Wifi Reconnected
description: Notify when EMS-ESP reconnects
triggers:
  - entity_id:
      - sensor.system_wifireconnects
    trigger: state
conditions: []
actions:
  - data:
      message: EMS-ESP has reconnected!
      title: EMS-ESP
    action: notify.mobile_app_my_iphone
mode: single
```

in 3.7.1-dev.8
