### ISSUE TITLE
Missing Homeassistant entities

### ISSUE THREAD

**Issue by mrfixit1** [emsesp/EMS-ESP32#38]
I'm having trouble restoring the shower timer and last ems data update info in HA after upgrading from esp8266 v194 to esp32 v3. Anyone have a suggestion where to look?

Config: bbqkees v0.8 interface, esp32, usb power, shower timer in ems UI enabled.

The ems-esp upgrade was very simple, thanks to the excellent readme and web UI: built and uploaded the firmware using platformio, configured the wifi and mqtt in AP mode, swapped the boards and updated a few entities in HA's ui-lovelace.yaml to their current names. The only items that confused me for a few minutes were not enabling Nested format together with HA MQTT Discovery, and disabling Invert/Hide LED to turn the blue LED off. 

All of my dashboard entries in HA are present and correct, except that the last ems data update date+time and last shower date+time are stuck on the date+time of the last core restart, while the shower duration stays blank.

I spent time going through the states list but can't find what I need. I deleted all 3 mqtt devices as recommended in esp8266 issue #643, which cleared a couple of double entries in the entity list but didn't fix my issue. Changing the lovelace mode in HA configuration from yaml to storage mode makes a big mess of my dashboard and I'm not keen on starting again from a fresh HA installation and reconfiguring the ems and other devices from scratch. 

What have I missed?

**Comment by proddy** [comment]
Nice to hear the upgrade to ESP32 went smooth, even on an old 0.8 gateway! On which ESM-ESP firmware version are you on?

Is the MQTT with the shower_data correct? This is what HA is using. If it is, then the problem is likely with a script. I'll need to check when I'm home to see what I have.

**Comment by mrfixit1** [comment]
v3.0.0

I'm seeing the expected shower data in HA's MQTT listener - see screenshot.
![Screenshot_20210325-185742](https://user-images.githubusercontent.com/43890144/112521794-33995200-8d9d-11eb-84bc-4bfde1863910.png)

**Comment by proddy** [comment]
Those last updated scripts were from v2 (ESP8266) and will not work with v3. You can basically delete all those ems-esp entries in the yaml files. Use Integrations->MQTT to add the Devices to your lovelace UI. The only thing you might want to add to a yaml file are custom names or icons.

Then for the shower I only have this:

I have this
sensors.yaml
```yaml

- platform: template
  sensors:
    showertime_time:
      friendly_name: 'Last shower at'
      value_template: '{{ as_timestamp(states.sensor.last_shower_duration.last_updated) | int | timestamp_custom("%H:%M on %a %-d %b") }}'

- platform: mqtt
  name: 'Last shower duration'
  state_topic: "ems-esp/shower_data"
  value_template: "{{ value_json.duration | is_defined }}"
```
