### ISSUE TITLE
RC30_N sets the wrong temperature with home assistant

### ISSUE THREAD

**Issue by jerome992** [emsesp/EMS-ESP32#395]
The RC30_N does not have an method the set the actual temperature. It is only possible to the the night or the day time temperature.

With HA the following is happening:

1.) the RC30_N is in night mode, with the following temperature (night:17, day:19)
2.) HA sends the following command: thermostat_hc1 day followed by a thermostat_hc1 20°C
3.) the EMS-ESP sends the head mode to the RC30_N, but the change is not applied immediately in the RC30_N.
4.) the EMS-ESP sends the temperature 20°C to night temperature of the the RC30_N, because it has still not received the ack from the RC30_N, that the mode has switched: (night:20, day:19)
5.) the RC30_N switch the mode to day. (night:20, day:19)

finally the RC30_N is in day mode with the wrong temperature of 19, because the temperature has been applied to the wrong mode.

A possible solution is provided as attachment: The new mode is saved in a temporary variable until the RC30_N has acknowledged the mode change.

Sincerely,
Jerome

[patch_rc30_n.txt](https://github.com/emsesp/EMS-ESP32/files/8237537/patch_rc30_n.txt)

**Comment by proddy** [comment]
nice @jerome992 that you identified an issue and have a fix for it! Could you do a Pull Request for this? It's easier to test and merge. thanks!

**Comment by proddy** [comment]
@MichaelDvP I think this is the last thing to go into v3.4 before we make it the next stable release

**Comment by MichaelDvP** [comment]
Hmm, i think it's not RC30 specific. 
Sending multiple commands in short time will always be critical. Better wait for each command for readback /validate.
Write commands to the bus should be executed fast, so they are put to top of queue. But sending multiple commands will execute the latest first if waiting for the bus poll. 
Nevertheless the solution will work, The wantedmode is set before the seltemp command is executed.

I don't know what HA do, but isn't it better to send `daytemp` command? Or is the climate sending both commands?
The `thermostat_hc1` subscription is not in v3.4, climate goes direct to seltemp/mode-command, but with the same result.

**Comment by jerome992** [comment]
It is specific to every thermostat that does not allow to set actual temperature, but that only allows to set a night or day temperature.

I have made the following tests with version 3.3.1:
1.) I changed the mode in the climate GUI and HA has emited ems-esp/thermostat_hc1=off
2.) I changed the temperature in the climate GUI and HA has emited ems-esp/thermostat_hc1=16.5
3.) I called the service climate.set_temperature and the HA has emited ems-esp/thermostat_hc1=heat0 followed immediately by a ems-esp/thermostat_hc1=15.0:
```
service: climate.set_temperature
data:
  temperature: 15
  hvac_mode: heat
target:
  entity_id: climate.thermostat_hc1
```
4.) I have applied a scene in HA and the HA has also emited ems-esp/thermostat_hc1=heat0 followed immediately by a ems-esp/thermostat_hc1=15.0.

I dont know how to wait for a feedback in HA, except to use a script to in HA like:
sequence:
```
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'heat'
    target:
      entity_id: climate.thermostat_hc1
  - delay:
      seconds: 30
  - service: climate.set_temperature
    data:
      temperature: 20
    target:
      entity_id: climate.thermostat_hc1
```
