### ISSUE TITLE
EMS-ESP Version v3.4.0b8: Please add manufacturer to EMS-ESP Thermostat

### ISSUE THREAD

**Issue by zibous** [emsesp/EMS-ESP32#407]
**Bug description**
*A clear and concise description of what the bug is. Mention which EMS-ESP version you're using.*

Homeassistant: The **manufacturer** is empty (missing) for the EMS-ESP Thermostat

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

![Bildschirmfoto 2022-03-22 um 10 04 59](https://user-images.githubusercontent.com/30198737/159445098-4f585801-bfae-4f89-a7a1-dfde1c611220.png)

```
unique_id: thermostat_datetime
command_topic: ems-heizung/thermostat/datetime
state_topic: ems-heizung/thermostat_data
name: Thermostat date/time
value_template: '{{value_json.datetime}}'
device:
  identifiers:
    - ems-esp-thermostat
  name: EMS-ESP Thermostat
  manufacturer: ''  <----
  model: RC300/RC310/Moduline 3000/1010H/CW400/Sense II
  via_device: ems-esp
platform: mqtt
```
