### ISSUE TITLE
Warm water problem - Junkers CERAPURMODUL + FW200 + IPM2

### ISSUE THREAD

**Issue by km4lin** [emsesp/EMS-ESP32#548]
I've been using EMS-ESP (ESP8266) for 2 years and it worked fine, but it is not developed anymore.
For warm water I've been using script:
```
repeat:
  count: '60'
  sequence:
    - service: mqtt.publish
      data:
        topic: ems-esp/boiler
        payload: '{"cmd":"wwtemp","data":48}'
    - delay: '00:01:00'
```
Yesterday I've been updated ESP8266 to ESP32 thanks to article: https://bbqkees-electronics.nl/wiki/gateway/upgrade-the-gateway-to-an-esp32.html with v3.4.1 version
And now I'm struggling with getting warm water activation.
Please help - how can I get warm water activated via telnet/mqtt?
On FW200 there is the button for warm water activation, is there some option to activate it via telnet/mqtt?
I'll be very grateful for any help.
Regards
