### ISSUE TITLE
Monitoring of energy consumption using an integrated smart meter interface

### ISSUE THREAD

**Issue by Oktonaut** [emsesp/EMS-ESP32#665]
**Is your feature request related to a problem? Please describe.**
In view of constantly rising energy prices, it would be desirable to be able to monitor consumption data in parallel with the EMS-ESP.

**Describe the solution you'd like**
Most gas and water meters have a pulse generator for a corresponding sensor (read contact or Hall sensor).
Modern electricity meters have an optical interface through which their data can be read with a corresponding reading head (SML via ttl).

**Describe alternatives you've considered**
There are already corresponding implementations in [Tasmota](https://tasmota.github.io/docs/Smart-Meter-Interface/) and [others](https://esphome.io/components/sml.html)... But it would be nice to be able to use resources and not have to start with another device.

**Additional context**
This would certainly help to identify optimization possibilities for energy saving.

**Comment by proddy** [comment]
To be honest, I'm not sure what you're asking. How would this work in theory? Should EMS-ESP fetch the data from these smart meter interfaces (like a P1 interface for 2 euros) and then do what with the data? Using an automation system (like Home Assistant) is better for consolidating and providing intelligence on the data sets. HA has this out of the box.

Happy to think this through with you. I just can't visualize it my head...

see also https://github.com/emsesp/EMS-ESP32/issues/399

**Comment by bbqkees** [comment]
In general the (P1) meter is in the meterboard/closet on the ground floor and the boiler in the attic.
So they are physically at another location, therefore it does not make sense to combine it with EMS-ESP in a single device.
Currently there are dozens of cheap solutions available for P1 meters.
Both EMS-ESP and the power meter readers just provide an interface to f.i. Home Assistant. Its HA who needs to do something with the data.

**Comment by Oktonaut** [comment]
EMS-ESP itself does not do anything with the data of the respective heating system, but only displays it on its web interface and serves as an intermediary to higher-level systems.

For me, it's really just about not having to provide and maintain an extra device for every small task, which in turn has a number of pins free and is hardly utilized with a single task. In this way, resources and also energy for additional power supply units of additional devices could be saved. Just like 1-Wire, this would be another nice option.

It is of course clear to me that meters and heating are usually not installed in the immediate vicinity of each other. But the EMS-ESP does not necessarily have to be mounted directly on the boiler, but can be operated anywhere on the EMS bus.
Personally, I prefer to lay 10 meters of cable than to install another device. Especially since this first has to be configured, then additional energy is consumed and ultimately it also has to be administered in the long run.

**Comment by zibous** [comment]
I do it with the gas meter (esp-home es32) via the `/ api / boiler` interface. 
With an `http_request.get`, the data is fetched from the EMS-ESP32 and then evaluated.

```yaml
## ################################################################
## ESP32 DEV  - GAS & WASSER 2021 - SENSOREN
## ESP32 NodeMCU Module WLAN WiFi Development Board mit CP2102
## ################################################################
esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

substitutions:
  platform: ESP32
  board: esp32dev
  device_name_short: "wug2022" # used by esp-home config
  friendly_name: "WUG2"
  device_description: "Gaszähler, Kaltwassertemperatur, Kaltwasserdruck, Gasverbrauch"
  update_interval: 10s
  impulsfactor: "0.100"
  appversion: "1.5.0"
  ems_esp_data: "http://ems-heizung.local/api/boiler"
  ## all used pins on ESP32
  gipo_puse_counter: GPIO19 # GASCOUNTER ZI-61 REED CONTACT

esphome:
  project:
    name: "OE9psj.esp32WUG2"
    version: ${appversion}

# ----------------------------------------------------------------
# Global variables
# initial_value: "29060.654"  11.06.2021
# ----------------------------------------------------------------
globals:

  - id: z61count
    type: int
    restore_value: yes
    initial_value: "0"

  - id: z61counter
    type: float
    restore_value: yes
    initial_value: "0.0"

  - id: z61pulse
    type: float
    restore_value: no
    initial_value: "0.0"

  - id: m3kw
    # factor to calculate kw = m3 * m3kw
    type: float
    restore_value: yes
    initial_value: "10.94"

  - id: gas_meter_totalm3
   # total used m3
    type: float
    restore_value: yes
    initial_value: "0.0"

  - id: gas_meter_boiler
    # total used m3 for warmwater boiler
    type: float
    restore_value: yes
    initial_value: "0.0"

  - id: gas_meter_heizung
    # total used m3 for heating
    type: float
    restore_value: yes
    initial_value: "0.0"

  - id: gas_meter_displayinital
    ## this is the inital value or value from the installation
    type: float
    restore_value: yes
    initial_value: "29060.654"

  - id: gas_meter_displayvalue
    ## this is the current value on the gasmeter display
    type: float
    restore_value: yes
    initial_value: "29246.433"

  - id: burnworkmin
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: wwworkm
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: heatworkmin
    type: float
    restore_value: yes
    initial_value: "0.00"


# ---------------------------------------
# Base packages wifi, timeserver...
# ---------------------------------------
packages:
  base: !include common/base.yaml
  base_global: !include common/base_global.yaml

# ----------------------------------------------------------------
# Native API Component
# ----------------------------------------------------------------
api:
  id: espapi
  port: 6053
  # Can be disabled by setting this to 0s. Defaults to 15min.
  reboot_timeout: 0s
  services:
    - service: set_gasmeterdisplay
      variables:
        my_newdisplayvalue: float
      then:
        - logger.log:
            format: "Update Gasmeter Display value: %.1f"
            args: [my_newdisplayvalue]
        - globals.set:
            id: gas_meter_displayvalue
            value: !lambda "return (my_newdisplayvalue);"
        - globals.set:
            id: z61counter
            value: !lambda "return (my_newdisplayvalue);"
        - globals.set:
            id: gas_meter_totalm3
            value: !lambda "return ((my_newdisplayvalue) - id(gas_meter_displayinital));"
        - globals.set:
            id: z61count
            value: !lambda "return ( ((my_newdisplayvalue) - id(gas_meter_displayinital))/${impulsfactor} );"
        - logger.log:
            format: "New Gasmeter Display value is: %.1f"
            args: [id(gas_meter_displayvalue)]

http_request:
  # timeout: 10s
  id: http_request_data

interval:
  interval: 10s
  then:
      - http_request.get:
          url: ${ems_esp_data}
          on_response:
            then:
                - lambda: |-
                    StaticJsonDocument<2048> doc;
                    DeserializationError error = deserializeJson(doc, id(http_request_data).get_string());
                    const char* isOn = "on";
                    if (error) {
                      ESP_LOGI("main", "ERROR Datasource EMS-ESP32");
                    }else{
                      const char* heatingactive = doc["heatingactive"]; // "off"
                      const char* ww3wayvalve = doc["ww3wayvalve"]; // "off"
                      const char* wwdisinfecting = doc["wwdisinfecting"]; // "off"
                      // state heater, warwwater
                      id(heater_swi).publish_state( std::string(heatingactive)=="on" );
                      id(boiler_swi).publish_state( std::string(ww3wayvalve)=="on" );
                      id(wwdisinfecting_swi).publish_state( std::string(wwdisinfecting)=="on" );
                      // runnings time
                      id(burnworkmin) = doc["burnworkmin"]; // 114326
                      id(heatworkmin) = doc["heatworkmin"]; // 104157
                      id(wwworkm) = doc["wwworkm"]; // 104157
                    }

# ----------------------------------------------------------------
# Switch to restart, reset all, reset bootcounter
# ----------------------------------------------------------------
switch:
  - platform: template
    name: ${friendly_name} reset all
    id: btnresetall
    turn_on_action:
      then:
        - lambda: |-
            id(boot_counter) = 0;
            id(z61counter) = 0.0;
            id(z61count) = 0;
            id(gas_meter_totalm3)= 0.0;
            id(gas_meter_displayvalue)= 0.0;
            id(daily_value)= 0.0;
            id(hour_value)= 0.0;
            id(bootcounter).update();
            id(gas_meter_display).update();
            id(gas_meter_total_m3).update();
            id(gas_meter_total_kw).update();
            id(gas_meter_total_kw_day).update();
        - logger.log: ${device_name_short} all values reset!
        - delay: 1s
        - switch.toggle: btnresetall

  - platform: template
    name:  EMS Heizkreis
    optimistic: true
    id: heater_swi

  - platform: template
    name: EMS Warmwasser
    optimistic: true
    id: boiler_swi

  - platform: template
    name: EMS Desinfizierung
    optimistic: true
    id: wwdisinfecting_swi

  - platform: template
    name: ${friendly_name} Boiler
    id: boilermode
    optimistic: true
    on_turn_on:
      - logger.log: "Switch Turned On!"
    on_turn_off:
      - logger.log: "Switch Turned Off!"

# ----------------------------------------------------------------
# GASCOUNTER ZI-61 REED CONTACT
# GPIO19 <-- o-RC-o <--- GND
#            o-10k ----> +5V2
# +++++++++++++++++++++++++++++++
# Gasmeter: Krom Schröder BK-G,25
# ++++++++++++++++++++++++++++++++
# Q_max: 4 m³/h
# Q_min: 0.025 m³/h
# V: 1.2 dm³
# p_max: 0.5 bar
# 1 imp = 0.1 m³
# ----------------------------------------------------------------
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP ## set ESP32 pin to input pull-up mode
      inverted: false
    name: ${friendly_name} Gaszähler Z-61 Impuls
    id: gassensor_state
    device_class: window
    filters:
      - delayed_off: 10ms
    ## This automation will be triggered when a button press ends,
    ## or in other words on the falling edge of the signal.
    on_release:
      then:
        - lambda: |-
            ESP_LOGI("main", " -------  Z-61 SET NEW VALUES !!!!!");
            id(z61pulse)=${impulsfactor};
            id(gas_meter_m3_current).publish_state(${impulsfactor});
            id(gas_meter_m3_current).update();
            id(z61count) += 1;
            id(z61counter) += ${impulsfactor};
            id(gas_meter_displayvalue) += ${impulsfactor};
            id(gas_meter_totalm3) += ${impulsfactor};
            id(daily_value) += ${impulsfactor};
            id(hour_value) += ${impulsfactor};
            id(gas_meter_display).update();
            id(gas_meter_total_m3).update();
            id(gas_meter_total_kw).update();
            id(gas_meter_total_kw_day).update();
            if (id(boilermode).state) {
              id(gas_meter_boiler) += ${impulsfactor};
            }else{
              id(gas_meter_heizung) += ${impulsfactor};
            };
        - delay: 500ms
        - lambda: |-
            id(z61pulse) = 0.00;
            id(gas_meter_m3_current).publish_state(0.00);
            id(gas_meter_m3_current).update();

# ----------------------------------------------------------------
# ALL SENSORS
# ----------------------------------------------------------------
sensor:
  - platform: template
    name: ${friendly_name} Gaszähler Anzeige
    id: gas_meter_display
    accuracy_decimals: 1
    unit_of_measurement: "m³"
    icon: "mdi:counter"
    device_class: gas
    update_interval: ${update_interval}
    lambda: |-
      return id(gas_meter_displayvalue);

  - platform: template
    name: ${friendly_name} Gaszähler aktuell
    id: gas_meter_m3_current
    state_class: measurement
    device_class: gas
    update_interval: ${update_interval}
    unit_of_measurement: "m³"
    accuracy_decimals: 2
    lambda: |-
      return (id(z61pulse));

  - platform: template
    name: ${friendly_name} Gaszähler Impulse
    id: gas_meter_impulse_count
    state_class: measurement
    update_interval: ${update_interval}
    accuracy_decimals: 0
    lambda: |-
      return (id(z61count));

  - platform: template
    name: ${friendly_name} Gasverbrauch gesamt
    id: gas_meter_total_m3
    accuracy_decimals: 1
    unit_of_measurement: "m³"
    device_class: gas
    state_class: total_increasing
    update_interval: 10s
    lambda: |-
      return id(gas_meter_totalm3);

  - platform: template
    name: ${friendly_name} Gasverbrauch Heizung
    id: gas_meter_heizung_m3
    accuracy_decimals: 1
    unit_of_measurement: "m³"
    device_class: gas
    state_class: total_increasing
    update_interval: 10s
    lambda: |-
      return id(gas_meter_heizung);

  - platform: template
    name: ${friendly_name} Gasverbrauch Boiler
    id: gas_meter_boiler_m3
    accuracy_decimals: 1
    unit_of_measurement: "m³"
    device_class: gas
    state_class: total_increasing
    update_interval: 10s
    lambda: |-
      return id(gas_meter_boiler);

  - platform: template
    name: ${friendly_name} Gasverbrauch heute
    id: gas_meter_total_m3_day
    unit_of_measurement: "m³"
    state_class: total_increasing
    accuracy_decimals: 1
    update_interval: ${update_interval}
    icon: mdi:gauge
    lambda: |-
      return (id(daily_value));

  - platform: template
    name: ${friendly_name} Gasverbrauch Stunde
    id: gas_meter_total_m3_hour
    unit_of_measurement: "m³"
    state_class: total_increasing
    accuracy_decimals: 1
    update_interval: ${update_interval}
    icon: mdi:gauge
    lambda: |-
      return (id(hour_value));

  - platform: template
    name: ${friendly_name} Kilowattstunde Gas gesamt
    id: gas_meter_total_kw
    accuracy_decimals: 2
    device_class: energy
    state_class: measurement
    update_interval: ${update_interval}
    unit_of_measurement: "kWh"
    lambda: |-
      return (id(gas_meter_totalm3) * id(m3kw));

  - platform: template
    name: ${friendly_name} Kilowattstunde Gas heute
    id: gas_meter_total_kw_day
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    update_interval: ${update_interval}
    accuracy_decimals: 2
    lambda: |-
      return (id(daily_value) * id(m3kw));

  - platform: template
    name: ${friendly_name} Kilowattstunde Gas Stunde
    id: gas_meter_total_kw_hour
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    update_interval: ${update_interval}
    accuracy_decimals: 2
    lambda: |-
      return (id(hour_value) * id(m3kw));

  - platform: template
    name: EMS Brennerzeit
    id: heater_burnworkmin
    update_interval: ${update_interval}
    unit_of_measurement: "s"
    accuracy_decimals: 0
    lambda: |-
      return id(burnworkmin)*60;

  - platform: template
    name: EMS Heizungkreiszeit
    id: heater_heatworkmin
    update_interval: ${update_interval}
    unit_of_measurement: "s"
    accuracy_decimals: 0
    lambda: |-
      return id(heatworkmin)*60;

  - platform: template
    name: EMS  Boilerzeit
    id: heater_wwworkm
    update_interval: ${update_interval}
    unit_of_measurement: "s"
    accuracy_decimals: 0
    lambda: |-
      return id(wwworkm)*60;

  - platform: template
    name: EMS Anteil Heizung
    id: heater_anteil
    update_interval: ${update_interval}
    unit_of_measurement: "%"
    accuracy_decimals: 2
    lambda: |-
      return (id(heatworkmin)/id(burnworkmin))*100;

  - platform: template
    name: EMS  Anteil Boiler
    id: boiler_anteil
    update_interval: ${update_interval}
    unit_of_measurement: "%"
    accuracy_decimals: 2
    lambda: |-
      return (id(wwworkm)/id(burnworkmin))*100;
      return id(wwworkm)*60;

text_sensor:
  - platform: template
    id: gasmeterdata
    update_interval: ${update_interval}
    # https://serverless.industries/2021/07/07/esphome-http-request-influxdb.html
    lambda: |-
        char buf[512];
        sprintf(buf, "%.3f|%.3f|%s",
               id(gas_meter_displayvalue),
               id(gas_meter_totalm3),
               id(systime).state.c_str()
               );
        std::string s = buf;
        return s;

logger:
  level: INFO


```
