### ISSUE TITLE
Add example of how to change EMS values from Home Assistant

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#95]
I'll be adding some examples to the [HA documentation](https://emsesp.github.io/docs/#/Home-Assistant) on how to easily use the new V3 API to change EMS values via widgets in a home assistant UI.

**Comment by proddy** [comment]
Files to change in Home Assistant

`configuration.yaml`:

```yaml
rest_command:
  emsesp:
    url: http://<IP address of EMS-ESP>/api/{{device}}
    method: POST
    headers:
      authorization: 'Bearer <Your Secure key from the UI>'
    content_type: 'application/json'
    payload: '{"name":"{{name}}","value":"{{value}}"}'

input_number:
  wwselected_temp:
    name: WW Selected Temperature
    min: 30
    max: 60
    step: 1
    icon: mdi:coolant-temperature
```

in `automations.yaml`:

```yaml
- id: 'change_ww_seltemp'
  alias: "change ww selected temp"
  trigger:
    platform: state
    entity_id: input_number.wwselected_temp
  action:
    service: rest_command.emsesp
    data:
      device: "boiler"
      name: "wwseltemp"
      value: "{{ states('input_number.wwselected_temp') | int }}"

- id: 'set_ww_seltemp'        
  alias: "set ww selected temp"
  trigger:
    platform: state
    entity_id: sensor.thermostat_hc1_selected_room_temperature
  action:
    service: input_number.set_value
    target:
      entity_id: input_number.wwselected_temp
    data:
      value: "{{ states('sensor.boiler_ww_selected_temperature') | int }}"
```

Then in your HA's lovelace UI add then entity called `input_number.wwselected_temp`.

Now in HA you can dynamically adjust the values. Like:

![Screenshot 2021-08-08 143712](https://user-images.githubusercontent.com/1230712/128632199-7815d649-40a8-4f11-99e3-eacc16bf53a4.png)

Check if it's working by going to `http://ems-esp/api/boiler/wwseltemp`
